-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/data-stash.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mws_data_stash (
  mwds_owner INT UNSIGNED NOT NULL,
  mwds_owner_type VARCHAR(255) NOT NULL,
  mwds_key VARCHAR(255) NOT NULL,
  mwds_touched BINARY(14) DEFAULT NULL,
  mwds_sha1 VARCHAR(40) NOT NULL,
  mwds_data LONGTEXT NOT NULL,
  INDEX mwds_lookup_index_unique (
    mwds_owner, mwds_owner_type, mwds_key
  )
) /*$wgDBTableOptions*/;
